### ISSUE TITLE
Variable length of "options"?

### ISSUE THREAD

**Issue by billbradley** [TIGER-AI-Lab/MMLU-Pro#14]
I was surprised to observe that the number of options varies between model evaluations.  Consider the eval_results directory `https://github.com/TIGER-AI-Lab/MMLU-Pro/tree/main/eval_results` and compare the results from `Mistral-7B-Instruct-v0.2` with `Meta-Llama-3_1-8B-Instruct`. Examining `question_id=2453`, I see two options from the first model:
```
 'options': ['Excess dopamine or sensitivity to dopamine could be a contributory factor.',
  'A lower rate of Schizophrenia diagnosed among Africa Americans.'],
```
but five options from the second model:
```
 'options': ['Excess dopamine or sensitivity to dopamine could be a contributory factor.',
  'A lower rate of Schizophrenia diagnosed among Africa Americans.',
  'Schizophrenia is primarily caused by poor lifestyle choices',
  'Schizophrenia can be completely cured through psychotherapy',
  'All schizophrenia patients exhibit severe personality splitting'],
```

Is this behavior expected?

**Comment by Wyyyb** [comment]
Thank you for your observation. You're correct - this discrepancy is due to our ongoing updates to the MMLU-Pro question bank. The difference you noticed likely reflects a correction made between evaluations of these two models.

Don't worry, though. These updates affect only a very small number of questions and have negligible impact on the overall evaluation performance metrics.

For more information on our question updates, you can check our dataset page at https://huggingface.co/datasets/TIGER-Lab/MMLU-Pro. This page provides visibility into our ongoing maintenance and improvements to the question bank.
