### ISSUE TITLE
Add Gemma 2 9B and 27B

### ISSUE THREAD

**Issue by carterprince** [TIGER-AI-Lab/MMLU-Pro#4]
I'm not sure the "correct" place to request a new model, so I'm just gonna make an issue here.

Hugging Face links:
- https://huggingface.co/google/gemma-2-9b-it
- https://huggingface.co/google/gemma-2-27b-it

They're also available on [Vertex](https://github.com/GoogleCloudPlatform/vertex-ai-samples/blob/main/notebooks/community/model_garden/model_garden_gemma2_deployment_on_vertex.ipynb) as `gemma-2-9b-it` and `gemma-2-27b-it`.

**Comment by wenhuchen** [comment]
Thanks for the reminder! We will work on it.

**Comment by Wyyyb** [comment]
The results of the gemma-2-9b and gemma-2-9b-it models have been updated on the leaderboard (https://huggingface.co/spaces/TIGER-Lab/MMLU-Pro). However, due to issues with the 27b vllm support (see https://github.com/vllm-project/vllm/pull/5908), we will update the corresponding results once this issue is resolved.

**Comment by Kyeongpil** [comment]
@Wyyyb  Hello, Is there any updates?

**Comment by Wyyyb** [comment]
The 9b models has been added, but it seems that the issues with support for the 27b models in vllm have not been resolved, https://github.com/vllm-project/vllm/issues/6387
