### ISSUE TITLE
Hunyuan Large & Athene V2

### ISSUE THREAD

**Issue by NSbuilder** [TIGER-AI-Lab/MMLU-Pro#44]
Please add:
https://huggingface.co/tencent/Tencent-Hunyuan-Large
https://huggingface.co/Nexusflow/Athene-V2-Chat

**Comment by wenhuchen** [comment]
Sure, we are working on it now.

**Comment by Wyyyb** [comment]
We have added Athene-V2-Chat's evaluation results to the leaderboard, achieving an impressive overall score of 0.7021. There are some issues with the vllm environment for the Hunyuan model that hasn't been resolved yet. We will update its score once vllm officially supports its model architecture.

**Comment by banghua-nexusflow** [comment]
Thank you @NSbuilder for the request, and @wenhuchen @Wyyyb for testing Athene-V2-Chat.

In fact we have also tested the MMLU-Pro of Athene-V2-Chat for multiple times, and its score generally ranges from 73.5 to 73.7 instead of around 70.0. I'm guess the potential reason could be the following:

1. We were using 0-shot instead of 5-shot in our testing, since the given 5-shot examples are usually quite concise and Athene-V2-Chat benefits from longer CoT in general. 
2. We were serving the model with vllm version 0.6.1.post2, as the latest version may have some bugs with Qwen generation.  See e.g. https://github.com/vllm-project/vllm/issues/9769. 

Could you please let us know if you still cannot reproduce our results? Happy to provide more details / the output files to help debug this process.

**Comment by wenhuchen** [comment]
@banghua-nexusflow would you mind submitting your evaluation results according to https://huggingface.co/spaces/TIGER-Lab/MMLU-Pro. So we can update your results based on your own reported number! Thanks!

**Comment by Wyyyb** [comment]
Yes, I reproduced your result by testing the 0-shot setting. The performance is: 
Athene-V2-Chat (0-shot), 0.7311,0.8689,0.7921,0.7473,0.7463,0.8081,0.5996,0.7164,0.6404,0.5095,0.8364,0.6293,0.7737,0.7857,0.7219
